import ListGames from "@/components/ListGames";
import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>Consumo de API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>Lista de jogos:</h1>
        <ListGames />
      </main>
    </>
  );
}
